version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.14.0
  aws-ecs: circleci/aws-ecs@1.3.0
workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          repo: "nginx"
          region: AWS_REGION
          tag: "${CIRCLE_SHA1}"
          dockerfile: ".circleci/images/nginx/Dockerfile"
          name: "nginx"
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          repo: "app"
          region: AWS_REGION
          tag: "${CIRCLE_SHA1}"
          dockerfile: ".circleci/images/php/Dockerfile"
          name: "app"
      - aws-ecs/deploy-service-update:
          requires:
            - "nginx"
            - "app"
          family: "todo-app"
          cluster-name: "todo-app"
          container-image-name-updates: "container=app,tag=${CIRCLE_SHA1}"